name: CD Pipeline Backend

on:
  workflow_run:
    workflows: ["CI Pipeline Backend"]
    branches: [ main, dev-backend ]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2

        run: |
          ssh -o StrictHostKeyChecking=no -l ubuntu 18.231.119.58 <<EOF

          IMAGE=\$(echo ghcr.io/\${{ github.repository }}-backend:\${{ steps.commit.outputs.short }} | tr '[:upper:]' '[:lower:]')

          # Stop and remove the running container
          
          CONTAINER_ID=\$(sudo docker ps --filter "publish=2000" -q)

          echo "Stopping container \$CONTAINER_ID"

          sudo docker stop \$CONTAINER_ID

          echo "Removing unused Docker images..."

          sudo docker image prune -a -f

          # Pull the latest image

          echo "Pulling image \$IMAGE"

          sudo docker pull \$IMAGE

          # Run the new container with environment variables
          echo "Running container \$IMAGE"

          sudo docker run -d -p 2000:2000 \\
            -e DB_USERNAME=\${{ secrets.DB_USERNAME }} \\
            -e DB_PASSWORD=\${{ secrets.DB_PASSWORD }} \\
            -e DB_HOST=\${{ secrets.DB_HOST }} \\
            -e DB_PORT=\${{ secrets.DB_PORT }} \\
            -e DB_NAME=\${{ secrets.DB_NAME }} \\
            \$IMAGE

          EOFs